
services:
  db:
    image: postgres:15
    container_name: backend_db
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: backend_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: backend
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 backend.asgi:application"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: backend_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  pgdata:
