# Generated by Django 5.2.3 on 2025-08-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('dates', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('google_maps_link', models.URLField()),
                ('img_src', models.URLField()),
                ('img_alt', models.CharField()),
            ],
        ),
    ]
